scheme: Pisces


sidebar:
  position: left

math: 
  mathjax:
    enable: true
  enable: true
  per_page: false

busuanzi_count:
  # count values only if the other configs are false
  enable: true

valine:
  enable: true
  appid: w5q6IP0osm99hRrYrGPtiWo2-gzGzoHsz
  appkey: bs1RDDouIyijDdev01eNL4hD
  recordIP: true
