scheme: Pisces

language: zh-Hans

sidebar:
  position: left

math: 
  mathjax:
    enable: true
  enable: true
  per_page: false

busuanzi_count:
  # count values only if the other configs are false
  enable: true
